<?php

  /**
   *  WARNING: This file is part of the core belief_theme_slug Theme Framework. DO NOT edit this file under any circumstances. Please do all modifications in the form of a child theme.
   *
   * File contains initialization of belief_theme_slug Design features created at init hook
   *
   *
   *
   * @package WordPress
   * @subpackage Belief Theme
   * @author  BeliefAgency
   * @license GPL-2.0+
   * @since Belief Theme Theme 1.1
   */


class Belief_Design {
  public $instance;

  public function __construct() {
    $this->instance =& $this;
    //initialize the theme structure
    add_action( 'init', array( $this, 'initialize' ) );

    //setup enqueue scripts
    add_action( 'wp_enqueue_scripts', array($this,'belief_scripts') );


    if (! function_exists('belief_setup')) {
      add_action( 'after_setup_theme', array($this, 'belief_setup') );
    }

    //filters for excerpt
    add_filter('the_excerpt', 'belief_excerpt');
    add_filter('excerpt_more', 'belief_excerpt_more');
    add_filter('excerpt_length', 'belief_excerpt_length');
  }

  public function initialize() {
    //initialize constants
    add_action( 'belief_init', array( $this, 'belief_constants') );

    //initialize frameworks
    add_action('belief_init', array( $this, 'belief_framework') );

    // initialize custom post types
    add_action( 'belief_init', array( $this, 'form_post_type' ) );

    //metaboxe module addon
    add_action( 'belief_init', array( $this, 'be_initialize_cmb_meta_boxes') );

    do_action('belief_init');
  }

  /**
      Constants & Framework

   */

  public function belief_constants() {

    require_once( dirname( __FILE__ ) . '/util/constants.php' );

  }

  public function belief_framework() {
    //classes
    require_once( BELIEF_ADMIN_DIR . '/belief_nav_menu.php' );
  }

  /**
      Register Post Types

   */

  /**
   * Register Custom Form Post Type
   * @link http://codex.wordpress.org/Function_Reference/register_post_type
   * @since 1.0
   */
  public function form_post_type() {
    $labels = array(
      'name' => __( 'Form Pages' ),
      'singular_name' => __( 'Form Page' ),
      'add_new' => __( 'Add New' ),
      'add_new_item' => __( 'Add New Form Page' ),
      'edit_item' => __( 'Edit Form Page' ),
      'new_item' => __( 'New Form Page' ),
      'view_item' => __( 'View Form Page' ),
      'search_items' => __( 'Search Form Pages' ),
      'not_found' =>  __( 'No Form Pages found' ),
      'not_found_in_trash' => __( 'No Form Pages found in trash' ),
      'menu_name' => __( 'Form Pages' ),
    );

    $args = array(
      'labels' => $labels,
      'public' => true,
      'publicly_queryable' => true,
      'show_ui' => true,
      'show_in_menu' => true,
      'query_var' => true,
      'rewrite' => array( 'slug' => 'form' ),
      'capability_type' => 'post',
      'has_archive' => true,
      'hierarchical' => false,
      'menu_position' => 5,
      'supports' => array('title','page-attributes')
    );

    register_post_type( 'belief_form_pages', $args );
  }

  /**
   * Initialize Metabox Class
   * see /lib/metabox/example-functions.php for more information
   *
   */
  public function be_initialize_cmb_meta_boxes() {
      if ( !class_exists( 'cmb_Meta_Box' ) ) {
        require_once( BELIEF_METABOX_DIR . '/init.php');
      }
  }

  /**
      Scripts

   */

  //register scripts
  public function belief_scripts() {

    //app stylesheet
    wp_enqueue_style( BELIEF_THEME_SLUG.'-app-style', get_template_directory_uri() . '/dist/css/app.css', array(), null);

      //add requireJ
    wp_enqueue_script( BELIEF_THEME_SLUG.'-require-js', get_template_directory_uri() . '/app/js/vendor/require.js', array(), null);

    $js_dir = array(
        'path' => get_stylesheet_directory_uri() . '/app/js/'
    );

      //add requireJS Config
    wp_enqueue_script( BELIEF_THEME_SLUG.'-config-requirejs', get_template_directory_uri() . '/app/js/app.js', array(), null);

    //localize the requireJS Config
    wp_localize_script( BELIEF_THEME_SLUG.'-config-requirejs', 'the_js_reference', $js_dir );



    //custom app stylesheet
    wp_enqueue_style( BELIEF_THEME_SLUG.'-custom-style', get_template_directory_uri() . '/style.css', array(), null);


    //add requireJS script
    // wp_localize_script( 'my-dependent', 'my_variable_reference', $my_js_dir );
  }


  /**
      Other

   */
  function belief_setup() {

    //enable post thumbnails
    add_theme_support( 'post-thumbnails' );
    set_post_thumbnail_size( 672, 372, true );

    //register primary menu
    register_nav_menus( array(
      'primary' => __( 'Top Primary Menu', 'belief_theme_slug' ),
    ) );
  }


  /**
   * Excerpt
   * @link http://codex.wordpress.org/Function_Reference/the_excerpt
   *
   */
  function belief_excerpt($output) {
    global $post;
    return "<p>".$output."</p>";
  }

  function belief_excerpt_more( $more ) {
    return ' ...';
  }

  function belief_excerpt_length($length) {
    return 100; // Or whatever you want the length to be.
  }
}

new Belief_Design;

require_once( dirname( __FILE__ )  . '/admin/belief_admin_init.php' );
require_once( dirname( __FILE__ )  . '/admin/belief_metaboxes_controller.php' );
