<?php

  /**
   *  WARNING: This file is part of the core belief_theme_slug Theme Framework. DO NOT edit this file under any circumstances. Please do all modifications in the form of a child theme.
   *
   * File contains initialization of belief_theme_slug Design features created at init hook
   *
   *
   *
   * @package WordPress
   * @subpackage BELIEF_THEME_TEMPLATE
   * @author  BeliefAgency
   * @license GPL-2.0+
   * @since BELIEF_THEME_TEMPLATE Theme 1.0
   */
class Belief_Theme_Classes_Design {
  var $instance;

  function __construct() {
    $this->instance =& $this;
    add_action( 'init', array( $this, 'initialize' ) );
  }

  function initialize() {
    //initialize constants
    add_action( 'belief_theme_slug_init', array( $this, 'belief_theme_slug_constants') );

    //initialize frameworks
    add_action('belief_theme_slug_init', array( $this, 'belief_theme_slug_load_framework') );

    // initialize custom post types
    add_action( 'belief_theme_slug_init', array( $this, 'sliders_post_type' ) );

    //metaboxes
    add_action( 'belief_theme_slug_init', array( $this, 'be_initialize_cmb_meta_boxes') );

    do_action('belief_theme_slug_init');
  }

  function belief_theme_slug_constants() {
    //directory location constants
    define( 'PARENT_DIR', get_template_directory() );
    define( 'belief_theme_slug_LIB_DIR', PARENT_DIR . '/lib' );
    define( 'belief_theme_slug_IMAGES_DIR', PARENT_DIR . '/images' );
    define( 'belief_theme_slug_INCLUDES_DIR', PARENT_DIR . '/includes' );
    define( 'belief_theme_slug_ADMIN_DIR', belief_theme_slug_LIB_DIR . '/admin' );
    define( 'belief_theme_slug_CLASSES_DIR', belief_theme_slug_LIB_DIR . '/classes' );
    define( 'belief_theme_slug_METABOX_DIR', belief_theme_slug_LIB_DIR . '/metabox' );
  }

  function belief_theme_slug_load_framework() {
    //classes
    require_once( belief_theme_slug_CLASSES_DIR . '/anchored_nav_menu.php' );
    require_once( belief_theme_slug_CLASSES_DIR . '/belief_theme_slug_nav_menu.php' );
  }

  /**
   * Register Sliders Post Type
   * @link http://codex.wordpress.org/Function_Reference/register_post_type
   * @since 1.0
   */
  function sliders_post_type() {
    $labels = array(
      'name' => __( 'Sliders' ),
      'singular_name' => __( 'Sliders' ),
      'add_new' => __( 'Add New' ),
      'add_new_item' => __( 'Add New Slider' ),
      'edit_item' => __( 'Edit Slider' ),
      'new_item' => __( 'New Slider' ),
      'view_item' => __( 'View Slider' ),
      'search_items' => __( 'Search Sliders' ),
      'not_found' =>  __( 'No Sliders found' ),
      'not_found_in_trash' => __( 'No Sliders found in trash' ),
      'menu_name' => __( 'Sliders' ),
    );

    $args = array(
      'labels' => $labels,
      'public' => true,
      'publicly_queryable' => true,
      'show_ui' => true,
      'show_in_menu' => true,
      'query_var' => true,
      'rewrite' => array( 'slug' => 'sliders' ),
      'capability_type' => 'post',
      'has_archive' => false,
      'hierarchical' => false,
      'menu_position' => 5,
      'supports' => array('title','editor', 'thumbnail', 'page-attributes')
    );

    register_post_type( 'belief_theme_slug_sliders', $args );
  }

  /**
   * Register Staff Post Type
   * @link http://codex.wordpress.org/Function_Reference/register_post_type
   * @since 1.0
   */
  function staff_post_type() {
    $labels = array(
      'name' => __( 'Staff' ),
      'singular_name' => __( 'Staff' ),
      'add_new' => __( 'Add New' ),
      'add_new_item' => __( 'Add New Staff' ),
      'edit_item' => __( 'Edit Staff' ),
      'new_item' => __( 'New Staff' ),
      'view_item' => __( 'View Staff' ),
      'search_items' => __( 'Search Staff' ),
      'not_found' =>  __( 'No Staff found' ),
      'not_found_in_trash' => __( 'No Staff found in trash' ),
      'menu_name' => __( 'Staff' ),
    );

    $args = array(
      'labels' => $labels,
      'public' => true,
      'publicly_queryable' => true,
      'show_ui' => true,
      'show_in_menu' => true,
      'query_var' => true,
      'rewrite' => array( 'slug' => 'staff' ),
      'capability_type' => 'post',
      'has_archive' => false,
      'hierarchical' => false,
      'menu_position' => 6,
      'supports' => array('title', 'page-attributes')
    );

    register_post_type( 'belief_theme_slug_staff', $args );
  }

  /**
   * Register Custom Form Post Type
   * @link http://codex.wordpress.org/Function_Reference/register_post_type
   * @since 1.0
   */
  function form_post_type() {
    $labels = array(
      'name' => __( 'Form Pages' ),
      'singular_name' => __( 'Form Page' ),
      'add_new' => __( 'Add New' ),
      'add_new_item' => __( 'Add New Form Page' ),
      'edit_item' => __( 'Edit Form Page' ),
      'new_item' => __( 'New Form Page' ),
      'view_item' => __( 'View Form Page' ),
      'search_items' => __( 'Search Form Pages' ),
      'not_found' =>  __( 'No Form Pages found' ),
      'not_found_in_trash' => __( 'No Form Pages found in trash' ),
      'menu_name' => __( 'Form Pages' ),
    );

    $args = array(
      'labels' => $labels,
      'public' => true,
      'publicly_queryable' => true,
      'show_ui' => true,
      'show_in_menu' => true,
      'query_var' => true,
      'rewrite' => array( 'slug' => 'form_pages' ),
      'capability_type' => 'post',
      'has_archive' => false,
      'hierarchical' => false,
      'menu_position' => 5,
      'supports' => array('title','page-attributes')
    );

    register_post_type( 'belief_theme_slug_form_pages', $args );
  }

  /**
   * Initialize Metabox Class
   * see /lib/metabox/example-functions.php for more information
   *
   */
  function be_initialize_cmb_meta_boxes() {
      if ( !class_exists( 'cmb_Meta_Box' ) ) {
        require_once( belief_theme_slug_METABOX_DIR . '/init.php');
      }
  }

}
new belief_theme_slug_Design;
